### ISSUE TITLE
GAForm- Weekly Task Info

### ISSUE THREAD

**Issue by rkgandhi** [russell190/UARK-GA-Manager#2]
So I was testing GAId 5 and there are currently 2 tasks under this ID. For some reason when I go to edit one of the tasks, both of them get updated with the same information. You can't edit one, without the other one's info changing (Hours, status, and comments only).

**Comment by wrjac** [comment]
Thanks for finding that! I should have set the update value to TaskID instead of GAID. This is now fixed in the latest [commit](https://github.com/russell190/UARK-GA-Manager/commit/158f6b9c8079cfd817dfb2b228006ede6f3aa209).
