### ISSUE TITLE
Make Assignments Tab 

### ISSUE THREAD

**Issue by rkgandhi** [russell190/UARK-GA-Manager#4]
All students are not displaying.

For simplicity's sake, should we display all GA's like you did for GA supervisors? Forget if they are available or not, just display all the GAs that are currently in Database and show semester assigned. I like how you did it for GA Supervisor.

**Comment by wrjac** [comment]
Gotcha. This should be fixed in my most recent [commit](https://github.com/russell190/UARK-GA-Manager/commit/5f174ec7c44c0edd39ea93edd06cb158eec0fc3c).
