### ISSUE TITLE
Director - Modify Assignments

### ISSUE THREAD

**Issue by rkgandhi** [russell190/UARK-GA-Manager#5]
So on that tab, I am supposed to be able to modify GA's and Hours of a given Supervisor. I am able to modify Hours successfully for the GAs. But when I go to modify a GA Name, it will change the name in the original Applicant table. For example, if I want to change your GA from Tim Tebow to Mary Smith, it will change it in the applicant table and Mary Smith will appear twice in the applicant table and Tim Tebow will not exist.

**Comment by wrjac** [comment]
This is kind of a quick and dirty fix (hence why the datagrid is really convoluted), but this will work for the presentation. See the latest commit changes [here](https://github.com/russell190/UARK-GA-Manager/commit/5efba501486d42ca0e33cdc30cf631b34b4a68f9).
